apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: pxbackup-ingress
  namespace: pxbackup
spec:
  rules:
  - host: backup.docs.portworx.com
    http:
      paths:
      - backend:
          serviceName: pxbackup-1-0
          servicePort: 80
        path: /
  - host: 1.0.backup.docs.portworx.com
    http:
      paths:
      - backend:
          serviceName: pxbackup-1-0
          servicePort: 80
        path: /
  tls:
  - hosts:
    - backup.docs.portworx.com
    secretName: ingress-pxbackup-tls
  - hosts:
    - 1.0.backup.docs.portworx.com
    secretName: ingress-pxbackup-1.0
